// sr_driver.c — thin host shell around statically-recompiled SAB code.
// Exposes MEM1 and the GekkoState to JS so a golden vector captured from NATIVE
// Dolphin can be staged, executed, and read back for a bit-exact diff.
#include <stdlib.h>
#include <emscripten.h>
#include "gekko_rt.h"

uint8_t  *g_ram = 0;
uint32_t  g_ram_size = 0;
uint32_t  g_fault = 0;

#define MEM1_SIZE 0x01800000u   // 24 MB, GameCube MEM1

static GekkoState g_st;

// Generated by sr.py alongside the translated bodies: address -> translated function.
int sr_dispatch(uint32_t addr, GekkoState *st);

EMSCRIPTEN_KEEPALIVE int sr_init(void) {
    if (!g_ram) { g_ram = (uint8_t *)calloc(1, MEM1_SIZE); g_ram_size = MEM1_SIZE; }
    return g_ram != 0;
}
EMSCRIPTEN_KEEPALIVE uint8_t     *sr_ram(void)       { return g_ram; }
EMSCRIPTEN_KEEPALIVE uint32_t     sr_ram_size(void)  { return g_ram_size; }
EMSCRIPTEN_KEEPALIVE GekkoState  *sr_state(void)     { return &g_st; }
EMSCRIPTEN_KEEPALIVE int          sr_state_size(void){ return (int)sizeof(GekkoState); }

// Dispatch by guest address — the same table a full build would generate.
EMSCRIPTEN_KEEPALIVE uint32_t sr_call(uint32_t addr) {
    g_fault = 0;
    if (!sr_dispatch(addr, &g_st)) return 0xBAD00000u | (addr & 0xFFFFu);
    return g_fault;
}
