// sr_driver.c — thin host shell around statically-recompiled SAB code.
// Exposes MEM1 and the GekkoState to JS so a golden vector captured from NATIVE
// Dolphin can be staged, executed, and read back for a bit-exact diff.
#include <stdlib.h>
#include <emscripten.h>
#include "gekko_rt.h"

uint8_t  *g_ram = 0;
uint32_t  g_ram_size = 0;
uint32_t  g_fault = 0;

#define MEM1_SIZE 0x01800000u   // 24 MB, GameCube MEM1

// EVERY build allocates a tail past MEM1 for the two guest windows that are not MEM1:
// the Gekko locked L1 cache at 0xE0000000 (256 KB of ordinary memory -- see the long
// note in gekko_rt.h) and WPAR at 0xCC008000 (4 KB, write-only MMIO).  It is not a
// verification-only affordance: without it gk_phys aliases 0xE0000030 onto MEM1
// offset 0x30 and a locked-cache store CORRUPTS GUEST LOW MEMORY in the shipping
// runtime.  `g_ram_size` still reports MEM1 only, so gk_ok's bound is unchanged.
#define SR_TAIL GK_TAIL_SIZE

static GekkoState g_st;

// Generated by sr.py alongside the translated bodies: address -> translated function.
int sr_dispatch(uint32_t addr, GekkoState *st);

EMSCRIPTEN_KEEPALIVE int sr_init(void) {
    if (!g_ram) { g_ram = (uint8_t *)calloc(1, MEM1_SIZE + SR_TAIL); g_ram_size = MEM1_SIZE; }
    return g_ram != 0;
}
EMSCRIPTEN_KEEPALIVE uint8_t     *sr_ram(void)       { return g_ram; }
EMSCRIPTEN_KEEPALIVE uint32_t     sr_ram_size(void)  { return g_ram_size; }
// Bytes allocated PAST g_ram_size: the locked-cache + WPAR tail.  Exported so the JS
// harness maps, poisons and stages exactly the buffer this build actually has,
// instead of hardcoding a layout that can drift out from under it.
EMSCRIPTEN_KEEPALIVE uint32_t     sr_tail_size(void) { return SR_TAIL; }
EMSCRIPTEN_KEEPALIVE GekkoState  *sr_state(void)     { return &g_st; }
EMSCRIPTEN_KEEPALIVE int          sr_state_size(void){ return (int)sizeof(GekkoState); }

// HOST-BOUNDARY HOOK.  NULL unless sr_host_os.c is linked in AND sr_os_init() ran,
// so every existing build keeps sr_extern's fault behaviour byte for byte.  When it
// is installed, a guest call to a host-implemented address (the OS context/interrupt
// primitives and SelectThread — see sr_host_os.h) is SERVICED instead of faulting.
// That is the mechanism by which a binary recomp gets MP4's "never compiled
// OSThread.c in" escape without having the source to omit.
int (*sr_host_hook)(GekkoState *, uint32_t) = 0;

// A call the generated file could not resolve to a translated function.  It FAULTS:
// silently returning would leave the caller's output nearly-right and hide the hole.
void sr_extern(GekkoState *st, uint32_t addr) {
    if (sr_host_hook && sr_host_hook(st, addr)) return;
    if (!g_fault) g_fault = 0xE0000000u | (addr & 0x00FFFFFFu);
}

// Indirect dispatch for blrl / bctr / bctrl.  A distinct fault prefix from sr_extern
// so a differential can tell "unresolved INDIRECT target" (0xE1) apart from "direct
// call outside the emitted set" (0xE0) — the two need different fixes.
void sr_indirect(GekkoState *st, uint32_t addr) {
    if (!sr_dispatch(addr, st)) {
        if (!g_fault) g_fault = 0xE1000000u | (addr & 0x00FFFFFFu);
    }
}

// Dispatch by guest address — the same table a full build would generate.
EMSCRIPTEN_KEEPALIVE uint32_t sr_call(uint32_t addr) {
    g_fault = 0;
    if (!sr_dispatch(addr, &g_st)) {
        // A host-bound address (sr.py --host) is deliberately absent from
        // sr_dispatch.  Let the harness call one directly rather than reporting it
        // as a missing translation; with no hook installed this is unreachable and
        // the 0xBAD0 code is returned exactly as before.
        if (sr_host_hook && sr_host_hook(&g_st, addr)) return g_fault;
        return 0xBAD00000u | (addr & 0xFFFFu);
    }
    return g_fault;
}

#ifdef SR_VERIFY
// ---------------------------------------------------------- fixture harness
// Only linked into the differential build.  `g_staged` marks every guest byte the
// native capture staged; `g_wlog` collects per-byte memory CHANGE events in order.
uint8_t *g_staged = 0;
uint32_t g_unstaged = 0;
uint32_t *g_wlog = 0;
uint32_t g_wlog_n = 0, g_wlog_cap = 0;

EMSCRIPTEN_KEEPALIVE uint8_t *sr_staged(void) {
    // Covers the tail too.  Locked-cache bytes are staged from the capture like any
    // MEM1 byte; a WPAR store marks its own bytes staged so a read-back of what this
    // invocation just wrote is legal, while a read of anything else in that window
    // trips the unstaged-read check.
    if (!g_staged) g_staged = (uint8_t *)calloc(1, MEM1_SIZE + SR_TAIL);
    return g_staged;
}
EMSCRIPTEN_KEEPALIVE uint32_t *sr_wlog(void) {
    if (!g_wlog) { g_wlog_cap = 1u << 20; g_wlog = (uint32_t *)calloc(g_wlog_cap * 2, 4); }
    return g_wlog;
}
EMSCRIPTEN_KEEPALIVE uint32_t sr_wlog_n(void)     { return g_wlog_n; }
EMSCRIPTEN_KEEPALIVE uint32_t sr_unstaged(void)   { return g_unstaged; }
EMSCRIPTEN_KEEPALIVE void sr_verify_reset(void) {
    g_wlog_n = 0; g_unstaged = 0;
    // Clear the tail too -- otherwise the second replay of a fixture (the ps1 = 0
    // arm) would read back what the first one wrote and the PS1-independence check
    // would be comparing against contaminated scratch.
    // CALL THIS *BEFORE* STAGING, NOT AFTER.  verify_fixture.mjs now stages locked-
    // cache bytes into the tail (they are real captured memory, not scratch), so a
    // reset issued after staging would wipe them and every locked-cache read would
    // come back as an unstaged-read fault.
    if (g_ram)    for (uint32_t i = 0; i < SR_TAIL; i++) g_ram[MEM1_SIZE + i] = 0;
    if (g_staged) for (uint32_t i = 0; i < SR_TAIL; i++) g_staged[MEM1_SIZE + i] = 0;
}
#endif
