// GENERATED by gamecube/recomp/sr/sr.py — STATIC RECOMPILATION of shipped PowerPC code.
// Source of truth: the game binary. No decompiled source was used.
#include "gekko_rt.h"

#ifndef CALL
#define CALL(a) do { g_fault = 0xC0DE0000u | ((a) & 0xFFFFu); } while (0)
#endif


// PSMTXConcat  @ 0x800ed368  (204 bytes, 51 instructions)
void fn_800ed368(GekkoState *st) {
    /* 800ed368: 9421ffc0 */
    { uint32_t _e = st->gpr[1] + (uint32_t)(-64); gk_w32(_e, st->gpr[1]); st->gpr[1] = _e; }
    /* 800ed36c: e0030000 */
    gk_psq_l(st, 0, (st->gpr[3] + (uint32_t)(0)), 0, 0);
    /* 800ed370: d9c10008 */
    gk_w64((st->gpr[1] + (uint32_t)(8)), st->ps0[14]);
    /* 800ed374: e0c40000 */
    gk_psq_l(st, 6, (st->gpr[4] + (uint32_t)(0)), 0, 0);
    /* 800ed378: 3cc0803b */
    st->gpr[6] = 0x803b0000u;
    /* 800ed37c: e0e40008 */
    gk_psq_l(st, 7, (st->gpr[4] + (uint32_t)(8)), 0, 0);
    /* 800ed380: d9e10010 */
    gk_w64((st->gpr[1] + (uint32_t)(16)), st->ps0[15]);
    /* 800ed384: 38c6d5c8 */
    st->gpr[6] = st->gpr[6] + (uint32_t)(-10808);
    /* 800ed388: dbe10028 */
    gk_w64((st->gpr[1] + (uint32_t)(40)), st->ps0[31]);
    /* 800ed38c: e1040010 */
    gk_psq_l(st, 8, (st->gpr[4] + (uint32_t)(16)), 0, 0);
    /* 800ed390: 11860018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[6]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[6]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed394: e0430010 */
    gk_psq_l(st, 2, (st->gpr[3] + (uint32_t)(16)), 0, 0);
    /* 800ed398: 11a70018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[7]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[7]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed39c: e3e60000 */
    gk_psq_l(st, 31, (st->gpr[6] + (uint32_t)(0)), 0, 0);
    /* 800ed3a0: 11c60098 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[6]), gk_force25(gk_bd(st->ps0[2])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[6]), gk_force25(gk_bd(st->ps0[2])))); gk_set_both(st, 14, _p0, _p1); }
    /* 800ed3a4: e1240018 */
    gk_psq_l(st, 9, (st->gpr[4] + (uint32_t)(24)), 0, 0);
    /* 800ed3a8: 11e70098 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[7]), gk_force25(gk_bd(st->ps0[2])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[7]), gk_force25(gk_bd(st->ps0[2])))); gk_set_both(st, 15, _p0, _p1); }
    /* 800ed3ac: e0230008 */
    gk_psq_l(st, 1, (st->gpr[3] + (uint32_t)(8)), 0, 0);
    /* 800ed3b0: 1188601e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[8]), gk_bd(st->ps1[0]), gk_bd(st->ps0[12]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[8]), gk_bd(st->ps1[0]), gk_bd(st->ps1[12]), 0)); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed3b4: e0630018 */
    gk_psq_l(st, 3, (st->gpr[3] + (uint32_t)(24)), 0, 0);
    /* 800ed3b8: 11c8709e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[8]), gk_bd(st->ps1[2]), gk_bd(st->ps0[14]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[8]), gk_bd(st->ps1[2]), gk_bd(st->ps1[14]), 0)); gk_set_both(st, 14, _p0, _p1); }
    /* 800ed3bc: e1440020 */
    gk_psq_l(st, 10, (st->gpr[4] + (uint32_t)(32)), 0, 0);
    /* 800ed3c0: 11a9681e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[9]), gk_bd(st->ps1[0]), gk_bd(st->ps0[13]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[9]), gk_bd(st->ps1[0]), gk_bd(st->ps1[13]), 0)); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed3c4: e1640028 */
    gk_psq_l(st, 11, (st->gpr[4] + (uint32_t)(40)), 0, 0);
    /* 800ed3c8: 11e9789e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[9]), gk_bd(st->ps1[2]), gk_bd(st->ps0[15]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[9]), gk_bd(st->ps1[2]), gk_bd(st->ps1[15]), 0)); gk_set_both(st, 15, _p0, _p1); }
    /* 800ed3cc: e0830020 */
    gk_psq_l(st, 4, (st->gpr[3] + (uint32_t)(32)), 0, 0);
    /* 800ed3d0: e0a30028 */
    gk_psq_l(st, 5, (st->gpr[3] + (uint32_t)(40)), 0, 0);
    /* 800ed3d4: 118a605c */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[10]), gk_bd(st->ps0[1]), gk_bd(st->ps0[12]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[10]), gk_bd(st->ps0[1]), gk_bd(st->ps1[12]), 0)); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed3d8: 11ab685c */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[11]), gk_bd(st->ps0[1]), gk_bd(st->ps0[13]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[11]), gk_bd(st->ps0[1]), gk_bd(st->ps1[13]), 0)); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed3dc: 11ca70dc */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[10]), gk_bd(st->ps0[3]), gk_bd(st->ps0[14]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[10]), gk_bd(st->ps0[3]), gk_bd(st->ps1[14]), 0)); gk_set_both(st, 14, _p0, _p1); }
    /* 800ed3e0: 11eb78dc */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[11]), gk_bd(st->ps0[3]), gk_bd(st->ps0[15]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[11]), gk_bd(st->ps0[3]), gk_bd(st->ps1[15]), 0)); gk_set_both(st, 15, _p0, _p1); }
    /* 800ed3e4: f1850000 */
    gk_psq_st(st, 12, (st->gpr[5] + (uint32_t)(0)), 0, 0);
    /* 800ed3e8: 10460118 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[6]), gk_force25(gk_bd(st->ps0[4])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[6]), gk_force25(gk_bd(st->ps0[4])))); gk_set_both(st, 2, _p0, _p1); }
    /* 800ed3ec: 11bf685e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[31]), gk_bd(st->ps1[1]), gk_bd(st->ps0[13]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[31]), gk_bd(st->ps1[1]), gk_bd(st->ps1[13]), 0)); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed3f0: 10070118 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[7]), gk_force25(gk_bd(st->ps0[4])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[7]), gk_force25(gk_bd(st->ps0[4])))); gk_set_both(st, 0, _p0, _p1); }
    /* 800ed3f4: f1c50010 */
    gk_psq_st(st, 14, (st->gpr[5] + (uint32_t)(16)), 0, 0);
    /* 800ed3f8: 11ff78de */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[31]), gk_bd(st->ps1[3]), gk_bd(st->ps0[15]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[31]), gk_bd(st->ps1[3]), gk_bd(st->ps1[15]), 0)); gk_set_both(st, 15, _p0, _p1); }
    /* 800ed3fc: f1a50008 */
    gk_psq_st(st, 13, (st->gpr[5] + (uint32_t)(8)), 0, 0);
    /* 800ed400: 1048111e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[8]), gk_bd(st->ps1[4]), gk_bd(st->ps0[2]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[8]), gk_bd(st->ps1[4]), gk_bd(st->ps1[2]), 0)); gk_set_both(st, 2, _p0, _p1); }
    /* 800ed404: 1009011e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[9]), gk_bd(st->ps1[4]), gk_bd(st->ps0[0]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[9]), gk_bd(st->ps1[4]), gk_bd(st->ps1[0]), 0)); gk_set_both(st, 0, _p0, _p1); }
    /* 800ed408: 104a115c */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[10]), gk_bd(st->ps0[5]), gk_bd(st->ps0[2]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[10]), gk_bd(st->ps0[5]), gk_bd(st->ps1[2]), 0)); gk_set_both(st, 2, _p0, _p1); }
    /* 800ed40c: c9c10008 */
    st->ps0[14] = gk_r64((st->gpr[1] + (uint32_t)(8)));
    /* 800ed410: f1e50018 */
    gk_psq_st(st, 15, (st->gpr[5] + (uint32_t)(24)), 0, 0);
    /* 800ed414: 100b015c */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[11]), gk_bd(st->ps0[5]), gk_bd(st->ps0[0]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[11]), gk_bd(st->ps0[5]), gk_bd(st->ps1[0]), 0)); gk_set_both(st, 0, _p0, _p1); }
    /* 800ed418: f0450020 */
    gk_psq_st(st, 2, (st->gpr[5] + (uint32_t)(32)), 0, 0);
    /* 800ed41c: 101f015e */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[31]), gk_bd(st->ps1[5]), gk_bd(st->ps0[0]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[31]), gk_bd(st->ps1[5]), gk_bd(st->ps1[0]), 0)); gk_set_both(st, 0, _p0, _p1); }
    /* 800ed420: c9e10010 */
    st->ps0[15] = gk_r64((st->gpr[1] + (uint32_t)(16)));
    /* 800ed424: f0050028 */
    gk_psq_st(st, 0, (st->gpr[5] + (uint32_t)(40)), 0, 0);
    /* 800ed428: cbe10028 */
    st->ps0[31] = gk_r64((st->gpr[1] + (uint32_t)(40)));
    /* 800ed42c: 38210040 */
    st->gpr[1] = st->gpr[1] + (uint32_t)(64);
    /* 800ed430: 4e800020 */
    return;
}

// PSMTXInverse  @ 0x800ed484  (248 bytes, 62 instructions)
void fn_800ed484(GekkoState *st) {
    /* 800ed484: e0038000 */
    gk_psq_l(st, 0, (st->gpr[3] + (uint32_t)(0)), 1, 0);
    /* 800ed488: e0230004 */
    gk_psq_l(st, 1, (st->gpr[3] + (uint32_t)(4)), 0, 0);
    /* 800ed48c: e0438010 */
    gk_psq_l(st, 2, (st->gpr[3] + (uint32_t)(16)), 1, 0);
    /* 800ed490: 10c104a0 */
    { uint64_t _x = st->ps1[1], _y = st->ps0[0]; st->ps0[6] = _x; st->ps1[6] = _y; }
    /* 800ed494: e0630014 */
    gk_psq_l(st, 3, (st->gpr[3] + (uint32_t)(20)), 0, 0);
    /* 800ed498: e0838020 */
    gk_psq_l(st, 4, (st->gpr[3] + (uint32_t)(32)), 1, 0);
    /* 800ed49c: 10e314a0 */
    { uint64_t _x = st->ps1[3], _y = st->ps0[2]; st->ps0[7] = _x; st->ps1[7] = _y; }
    /* 800ed4a0: e0a30024 */
    gk_psq_l(st, 5, (st->gpr[3] + (uint32_t)(36)), 0, 0);
    /* 800ed4a4: 116301b2 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[3]), gk_force25(gk_bd(st->ps0[6])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[3]), gk_force25(gk_bd(st->ps1[6])))); gk_set_both(st, 11, _p0, _p1); }
    /* 800ed4a8: 11a501f2 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[5]), gk_force25(gk_bd(st->ps0[7])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[5]), gk_force25(gk_bd(st->ps1[7])))); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed4ac: 110524a0 */
    { uint64_t _x = st->ps1[5], _y = st->ps0[4]; st->ps0[8] = _x; st->ps1[8] = _y; }
    /* 800ed4b0: 116159f8 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[1]), gk_bd(st->ps0[7]), gk_bd(st->ps0[11]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[1]), gk_bd(st->ps1[7]), gk_bd(st->ps1[11]), 1)); gk_set_both(st, 11, _p0, _p1); }
    /* 800ed4b4: 11810232 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[1]), gk_force25(gk_bd(st->ps0[8])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[1]), gk_force25(gk_bd(st->ps1[8])))); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed4b8: 11a36a38 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[3]), gk_bd(st->ps0[8]), gk_bd(st->ps0[13]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[3]), gk_bd(st->ps1[8]), gk_bd(st->ps1[13]), 1)); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed4bc: 11430132 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[3]), gk_force25(gk_bd(st->ps0[4])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[3]), gk_force25(gk_bd(st->ps1[4])))); gk_set_both(st, 10, _p0, _p1); }
    /* 800ed4c0: 118561b8 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[5]), gk_bd(st->ps0[6]), gk_bd(st->ps0[12]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[5]), gk_bd(st->ps1[6]), gk_bd(st->ps1[12]), 1)); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed4c4: 11200172 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[0]), gk_force25(gk_bd(st->ps0[5])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[0]), gk_force25(gk_bd(st->ps1[5])))); gk_set_both(st, 9, _p0, _p1); }
    /* 800ed4c8: 110100b2 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[1]), gk_force25(gk_bd(st->ps0[2])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[1]), gk_force25(gk_bd(st->ps1[2])))); gk_set_both(st, 8, _p0, _p1); }
    /* 800ed4cc: 10c63028 */
    { float _p0 = gk_force_single(gk_ni_sub(gk_bd(st->ps0[6]), gk_bd(st->ps0[6]))); float _p1 = gk_force_single(gk_ni_sub(gk_bd(st->ps1[6]), gk_bd(st->ps1[6]))); gk_set_both(st, 6, _p0, _p1); }
    /* 800ed4d0: 11425178 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[2]), gk_bd(st->ps0[5]), gk_bd(st->ps0[10]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[2]), gk_bd(st->ps1[5]), gk_bd(st->ps1[10]), 1)); gk_set_both(st, 10, _p0, _p1); }
    /* 800ed4d4: 10e00372 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[0]), gk_force25(gk_bd(st->ps0[13])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[0]), gk_force25(gk_bd(st->ps1[13])))); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed4d8: 11214938 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[1]), gk_bd(st->ps0[4]), gk_bd(st->ps0[9]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[1]), gk_bd(st->ps1[4]), gk_bd(st->ps1[9]), 1)); gk_set_both(st, 9, _p0, _p1); }
    /* 800ed4dc: 10e23b3a */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[2]), gk_bd(st->ps0[12]), gk_bd(st->ps0[7]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[2]), gk_bd(st->ps1[12]), gk_bd(st->ps1[7]), 0)); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed4e0: 110040f8 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[0]), gk_bd(st->ps0[3]), gk_bd(st->ps0[8]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[0]), gk_bd(st->ps1[3]), gk_bd(st->ps1[8]), 1)); gk_set_both(st, 8, _p0, _p1); }
    /* 800ed4e4: 10e43afa */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[4]), gk_bd(st->ps0[11]), gk_bd(st->ps0[7]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[4]), gk_bd(st->ps1[11]), gk_bd(st->ps1[7]), 0)); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed4e8: 10073040 */
    { double _a = gk_bd(st->ps0[7]), _b = gk_bd(st->ps0[6]); uint32_t _v = (_a != _a || _b != _b) ? 1u : (_a < _b) ? 8u : (_a > _b) ? 4u : 2u; gk_set_cr(st, 0, _v); }
    /* 800ed4ec: 4082000c */
    if ((gk_cr_bit(st, 2) == 0)) goto L_800ed4f8;
    /* 800ed4f0: 38600000 */
    st->gpr[3] = 0x00000000u;
    /* 800ed4f4: 4e800020 */
    return;
L_800ed4f8:;
    /* 800ed4f8: ec003830 */
    { float _r = gk_force_single(gk_fres(gk_bd(st->ps0[7]))); st->ps0[0] = gk_db((double)_r); st->ps1[0] = st->ps0[0]; }
    /* 800ed4fc: 10c0002a */
    { float _p0 = gk_force_single(gk_ni_add(gk_bd(st->ps0[0]), gk_bd(st->ps0[0]))); float _p1 = gk_force_single(gk_ni_add(gk_bd(st->ps1[0]), gk_bd(st->ps1[0]))); gk_set_both(st, 6, _p0, _p1); }
    /* 800ed500: 10a00032 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[0]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[0]), gk_force25(gk_bd(st->ps1[0])))); gk_set_both(st, 5, _p0, _p1); }
    /* 800ed504: 1007317c */
    { float _p0 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[7]), gk_bd(st->ps0[5]), gk_bd(st->ps0[6]), 1))); float _p1 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[7]), gk_bd(st->ps1[5]), gk_bd(st->ps1[6]), 1))); gk_set_both(st, 0, _p0, _p1); }
    /* 800ed508: c023000c */
    st->ps0[1] = gk_cvt_to_double(gk_r32((st->gpr[3] + (uint32_t)(12))));
    st->ps1[1] = st->ps0[1];
    /* 800ed50c: 11ad0018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[13]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[13]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 13, _p0, _p1); }
    /* 800ed510: c043001c */
    st->ps0[2] = gk_cvt_to_double(gk_r32((st->gpr[3] + (uint32_t)(28))));
    st->ps1[2] = st->ps0[2];
    /* 800ed514: 118c0018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[12]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[12]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 12, _p0, _p1); }
    /* 800ed518: c063002c */
    st->ps0[3] = gk_cvt_to_double(gk_r32((st->gpr[3] + (uint32_t)(44))));
    st->ps1[3] = st->ps0[3];
    /* 800ed51c: 116b0018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[11]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[11]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 11, _p0, _p1); }
    /* 800ed520: 10ad6420 */
    { uint64_t _x = st->ps0[13], _y = st->ps0[12]; st->ps0[5] = _x; st->ps1[5] = _y; }
    /* 800ed524: 114a0018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[10]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[10]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 10, _p0, _p1); }
    /* 800ed528: 108d64e0 */
    { uint64_t _x = st->ps1[13], _y = st->ps1[12]; st->ps0[4] = _x; st->ps1[4] = _y; }
    /* 800ed52c: 11290018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[9]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[9]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 9, _p0, _p1); }
    /* 800ed530: f0a40000 */
    gk_psq_st(st, 5, (st->gpr[4] + (uint32_t)(0)), 0, 0);
    /* 800ed534: 10cd0072 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[13]), gk_force25(gk_bd(st->ps0[1])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[13]), gk_force25(gk_bd(st->ps1[1])))); gk_set_both(st, 6, _p0, _p1); }
    /* 800ed538: f0840010 */
    gk_psq_st(st, 4, (st->gpr[4] + (uint32_t)(16)), 0, 0);
    /* 800ed53c: 11080018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[8]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[8]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 8, _p0, _p1); }
    /* 800ed540: 10cc30ba */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[12]), gk_bd(st->ps0[2]), gk_bd(st->ps0[6]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[12]), gk_bd(st->ps1[2]), gk_bd(st->ps1[6]), 0)); gk_set_both(st, 6, _p0, _p1); }
    /* 800ed544: f1448020 */
    gk_psq_st(st, 10, (st->gpr[4] + (uint32_t)(32)), 1, 0);
    /* 800ed548: 10cb30fe */
    { float _p0 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[11]), gk_bd(st->ps0[3]), gk_bd(st->ps0[6]), 0))); float _p1 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[11]), gk_bd(st->ps1[3]), gk_bd(st->ps1[6]), 0))); gk_set_both(st, 6, _p0, _p1); }
    /* 800ed54c: f1248024 */
    gk_psq_st(st, 9, (st->gpr[4] + (uint32_t)(36)), 1, 0);
    /* 800ed550: 10ea0072 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[10]), gk_force25(gk_bd(st->ps0[1])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[10]), gk_force25(gk_bd(st->ps1[1])))); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed554: 10ab3420 */
    { uint64_t _x = st->ps0[11], _y = st->ps0[6]; st->ps0[5] = _x; st->ps1[5] = _y; }
    /* 800ed558: f1048028 */
    gk_psq_st(st, 8, (st->gpr[4] + (uint32_t)(40)), 1, 0);
    /* 800ed55c: 108b34e0 */
    { uint64_t _x = st->ps1[11], _y = st->ps1[6]; st->ps0[4] = _x; st->ps1[4] = _y; }
    /* 800ed560: f0a40008 */
    gk_psq_st(st, 5, (st->gpr[4] + (uint32_t)(8)), 0, 0);
    /* 800ed564: 10e938ba */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[9]), gk_bd(st->ps0[2]), gk_bd(st->ps0[7]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[9]), gk_bd(st->ps1[2]), gk_bd(st->ps1[7]), 0)); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed568: f0840018 */
    gk_psq_st(st, 4, (st->gpr[4] + (uint32_t)(24)), 0, 0);
    /* 800ed56c: 10e838fe */
    { float _p0 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[8]), gk_bd(st->ps0[3]), gk_bd(st->ps0[7]), 0))); float _p1 = gk_negns_f(gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[8]), gk_bd(st->ps1[3]), gk_bd(st->ps1[7]), 0))); gk_set_both(st, 7, _p0, _p1); }
    /* 800ed570: 38600001 */
    st->gpr[3] = 0x00000001u;
    /* 800ed574: f0e4802c */
    gk_psq_st(st, 7, (st->gpr[4] + (uint32_t)(44)), 1, 0);
    /* 800ed578: 4e800020 */
    return;
}

// PSMTXMultVec  @ 0x800edab8  (84 bytes, 21 instructions)
void fn_800edab8(GekkoState *st) {
    /* 800edab8: e0040000 */
    gk_psq_l(st, 0, (st->gpr[4] + (uint32_t)(0)), 0, 0);
    /* 800edabc: e0430000 */
    gk_psq_l(st, 2, (st->gpr[3] + (uint32_t)(0)), 0, 0);
    /* 800edac0: e0248008 */
    gk_psq_l(st, 1, (st->gpr[4] + (uint32_t)(8)), 1, 0);
    /* 800edac4: 10820032 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[2]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[2]), gk_force25(gk_bd(st->ps1[0])))); gk_set_both(st, 4, _p0, _p1); }
    /* 800edac8: e0630008 */
    gk_psq_l(st, 3, (st->gpr[3] + (uint32_t)(8)), 0, 0);
    /* 800edacc: 10a3207a */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[3]), gk_bd(st->ps0[1]), gk_bd(st->ps0[4]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[3]), gk_bd(st->ps1[1]), gk_bd(st->ps1[4]), 0)); gk_set_both(st, 5, _p0, _p1); }
    /* 800edad0: e1030010 */
    gk_psq_l(st, 8, (st->gpr[3] + (uint32_t)(16)), 0, 0);
    /* 800edad4: 10c52994 */
    { float _p0 = gk_force_single(gk_ni_add(gk_bd(st->ps0[5]), gk_bd(st->ps1[5]))); float _p1 = gk_force_single(gk_bd(st->ps1[6])); gk_set_both(st, 6, _p0, _p1); }
    /* 800edad8: e1230018 */
    gk_psq_l(st, 9, (st->gpr[3] + (uint32_t)(24)), 0, 0);
    /* 800edadc: 11480032 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[8]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[8]), gk_force25(gk_bd(st->ps1[0])))); gk_set_both(st, 10, _p0, _p1); }
    /* 800edae0: f0c58000 */
    gk_psq_st(st, 6, (st->gpr[5] + (uint32_t)(0)), 1, 0);
    /* 800edae4: 1169507a */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[9]), gk_bd(st->ps0[1]), gk_bd(st->ps0[10]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[9]), gk_bd(st->ps1[1]), gk_bd(st->ps1[10]), 0)); gk_set_both(st, 11, _p0, _p1); }
    /* 800edae8: e0430020 */
    gk_psq_l(st, 2, (st->gpr[3] + (uint32_t)(32)), 0, 0);
    /* 800edaec: 118b5b14 */
    { float _p0 = gk_force_single(gk_ni_add(gk_bd(st->ps0[11]), gk_bd(st->ps1[11]))); float _p1 = gk_force_single(gk_bd(st->ps1[12])); gk_set_both(st, 12, _p0, _p1); }
    /* 800edaf0: e0630028 */
    gk_psq_l(st, 3, (st->gpr[3] + (uint32_t)(40)), 0, 0);
    /* 800edaf4: 10820032 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[2]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[2]), gk_force25(gk_bd(st->ps1[0])))); gk_set_both(st, 4, _p0, _p1); }
    /* 800edaf8: f1858004 */
    gk_psq_st(st, 12, (st->gpr[5] + (uint32_t)(4)), 1, 0);
    /* 800edafc: 10a3207a */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[3]), gk_bd(st->ps0[1]), gk_bd(st->ps0[4]), 0)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[3]), gk_bd(st->ps1[1]), gk_bd(st->ps1[4]), 0)); gk_set_both(st, 5, _p0, _p1); }
    /* 800edb00: 10c52994 */
    { float _p0 = gk_force_single(gk_ni_add(gk_bd(st->ps0[5]), gk_bd(st->ps1[5]))); float _p1 = gk_force_single(gk_bd(st->ps1[6])); gk_set_both(st, 6, _p0, _p1); }
    /* 800edb04: f0c58008 */
    gk_psq_st(st, 6, (st->gpr[5] + (uint32_t)(8)), 1, 0);
    /* 800edb08: 4e800020 */
    return;
}

// PSVECCrossProduct  @ 0x800ede34  (60 bytes, 15 instructions)
void fn_800ede34(GekkoState *st) {
    /* 800ede34: e0240000 */
    gk_psq_l(st, 1, (st->gpr[4] + (uint32_t)(0)), 0, 0);
    /* 800ede38: c0430008 */
    st->ps0[2] = gk_cvt_to_double(gk_r32((st->gpr[3] + (uint32_t)(8))));
    st->ps1[2] = st->ps0[2];
    /* 800ede3c: e0030000 */
    gk_psq_l(st, 0, (st->gpr[3] + (uint32_t)(0)), 0, 0);
    /* 800ede40: 10c10ca0 */
    { uint64_t _x = st->ps1[1], _y = st->ps0[1]; st->ps0[6] = _x; st->ps1[6] = _y; }
    /* 800ede44: c0640008 */
    st->ps0[3] = gk_cvt_to_double(gk_r32((st->gpr[4] + (uint32_t)(8))));
    st->ps1[3] = st->ps0[3];
    /* 800ede48: 108100b2 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[1]), gk_force25(gk_bd(st->ps0[2])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[1]), gk_force25(gk_bd(st->ps1[2])))); gk_set_both(st, 4, _p0, _p1); }
    /* 800ede4c: 10e10018 */
    { float _p0 = gk_force_single(gk_ni_mul(gk_bd(st->ps0[1]), gk_force25(gk_bd(st->ps0[0])))); float _p1 = gk_force_single(gk_ni_mul(gk_bd(st->ps1[1]), gk_force25(gk_bd(st->ps0[0])))); gk_set_both(st, 7, _p0, _p1); }
    /* 800ede50: 10a020f8 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[0]), gk_bd(st->ps0[3]), gk_bd(st->ps0[4]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[0]), gk_bd(st->ps1[3]), gk_bd(st->ps1[4]), 1)); gk_set_both(st, 5, _p0, _p1); }
    /* 800ede54: 110039b8 */
    { float _p0 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps0[0]), gk_bd(st->ps0[6]), gk_bd(st->ps0[7]), 1)); float _p1 = gk_force_single(gk_ni_madd_single(gk_bd(st->ps1[0]), gk_bd(st->ps1[6]), gk_bd(st->ps1[7]), 1)); gk_set_both(st, 8, _p0, _p1); }
    /* 800ede58: 11252ce0 */
    { uint64_t _x = st->ps1[5], _y = st->ps1[5]; st->ps0[9] = _x; st->ps1[9] = _y; }
    /* 800ede5c: 11454460 */
    { uint64_t _x = st->ps0[5], _y = st->ps1[8]; st->ps0[10] = _x; st->ps1[10] = _y; }
    /* 800ede60: f1258000 */
    gk_psq_st(st, 9, (st->gpr[5] + (uint32_t)(0)), 1, 0);
    /* 800ede64: 11405050 */
    st->ps0[10] = st->ps0[10] ^ 0x8000000000000000ull; st->ps1[10] = st->ps1[10] ^ 0x8000000000000000ull;
    /* 800ede68: f1450004 */
    gk_psq_st(st, 10, (st->gpr[5] + (uint32_t)(4)), 0, 0);
    /* 800ede6c: 4e800020 */
    return;
}

int sr_dispatch(uint32_t addr, GekkoState *st) {
    switch (addr) {
    case 0x800ed368u: fn_800ed368(st); return 1;   /* PSMTXConcat */
    case 0x800ed484u: fn_800ed484(st); return 1;   /* PSMTXInverse */
    case 0x800edab8u: fn_800edab8(st); return 1;   /* PSMTXMultVec */
    case 0x800ede34u: fn_800ede34(st); return 1;   /* PSVECCrossProduct */
    default: return 0;
    }
}
