#!/usr/bin/env python3
"""gen_psmtx_goldens_header.py — emit gamecube/bementalJIT/tests/psmtx_goldens.h from
psmtx_goldens.json (produced by golden_invoke_psmtx.py). The browser test can't read a
file, so the native golden vectors are embedded as C arrays. Each BE 4-byte float group
becomes the u32 VALUE a guest lwz/psq_l returns (== what the fixture's ppc_read32 stub
serves and the existing test encodes), so romtx/src/dst compare bit-exact in the JIT."""
import json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.environ.get("GOLDEN_IN", os.path.join(REPO, "gamecube/bementalJIT/tests/psmtx_goldens.json"))
OUT = os.path.join(REPO, "gamecube/bementalJIT/tests/psmtx_goldens.h")


def words(hexstr):
    b = bytes.fromhex(hexstr)
    assert len(b) % 4 == 0
    return [int.from_bytes(b[i:i + 4], "big") for i in range(0, len(b), 4)]


def main():
    d = json.load(open(SRC))
    lines = ["// GENERATED by gamecube/tools/gen_psmtx_goldens_header.py — DO NOT EDIT.",
             "// Native PSMTXROMultVecArray goldens (MP4 oracle, interpreter, GDB direct-invoke).",
             "// romtx = PSMTXReorder output (12 words); src/dst = Vec3 arrays (count*3 words).",
             "// Values are guest-word u32 (big-endian float bits) as ppc_read32/write32 deals in.",
             "#pragma once", "#include <cstdint>", "",
             "struct PsmtxGolden {",
             "    const char* name; uint32_t count;",
             "    const uint32_t* romtx;   // 12 words",
             "    const uint32_t* src;     // count*3 words",
             "    const uint32_t* dst;     // count*3 words (expected native output)",
             "};", ""]
    tab = []
    for i, r in enumerate(d):
        rm = words(r["romtx"]); sc = words(r["src"]); ds = words(r["dst"])
        assert len(rm) == 12, f"{r['name']} romtx {len(rm)}"
        assert len(sc) == r["count"] * 3 and len(ds) == r["count"] * 3
        def emit(nm, arr):
            lines.append(f"static const uint32_t {nm}[{len(arr)}] = {{" +
                         ", ".join(f"0x{w:08x}" for w in arr) + "};")
        emit(f"g_pg_rm_{i}", rm); emit(f"g_pg_sc_{i}", sc); emit(f"g_pg_ds_{i}", ds)
        tab.append(f'    {{ "{r["name"]}", {r["count"]}, g_pg_rm_{i}, g_pg_sc_{i}, g_pg_ds_{i} }}')
    lines.append("")
    lines.append(f"static const PsmtxGolden k_psmtx_goldens[{len(d)}] = {{")
    lines.append(",\n".join(tab))
    lines.append("};")
    lines.append(f"static const unsigned k_psmtx_goldens_n = {len(d)};")
    lines.append("")
    open(OUT, "w").write("\n".join(lines))
    print(f"wrote {OUT}: {len(d)} goldens", file=sys.stderr)


if __name__ == "__main__":
    main()
