service: my-nextjs-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    NODE_ENV: production
  lambdaHashingVersion: '20201221'

functions:
  next:
    handler: .next/serverless/pages/index.js
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    memorySize: 1024
    timeout: 10
    package:
      patterns:
        - 'pages/**'
        - 'public/**'
        - '.next/**'
        - 'node_modules/**'

plugins:
  - serverless-nextjs-plugin
