#ifndef GC_RECOMP_SIG_FIXES_H
#define GC_RECOMP_SIG_FIXES_H
// [wasm-recomp] AUTO-GENERATED by gen_sig_fixes.py. Exact RETURN TYPES for the
// decomp's mwcc-tolerated decl!=def functions (implicit-int callers vs
// void/float/double definitions). K&R args = no arg-type clash with the real
// headers. Return types verified against the byte-matching build/main.elf.
#include <dolphin/mtx/GeoTypes.h>
#endif
