const fs = require('fs');
const vert = fs.readFileSync('wgsl/dolphin_vk.vert.wgsl', 'utf8');
const frag = fs.readFileSync('wgsl/dolphin_vk.frag.wgsl', 'utf8');
// Sanity: ensure delimiter cannot appear inside the source.
const delim = 'WGSL';
if (vert.includes(')' + delim + '"') || frag.includes(')' + delim + '"'))
  throw new Error('delimiter collision');
const hdr = `// Copyright 2026 Dolphin Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// GENERATED by gamecube/wgsl/gen_wgsl_header.cjs from the naga-translated Vulkan-path
// ubershaders (gamecube/wgsl/dolphin_vk.{vert,frag}.wgsl). Do NOT hand-edit; regenerate
// from the .wgsl sources if the ubershader changes. These are the pre-translated WGSL
// uber vertex/fragment shaders embedded for Chunk B1 (CreateShaderFromSource returns these
// verbatim per stage; no runtime GLSL->WGSL translation).
//
// Binding scheme (must match the WGPUBindGroupLayouts built in WGPUGfx.cpp):
//   @group(0) @binding(1) var<uniform> VSBlock   (vertex)
//   @group(0) @binding(0) var<uniform> PSBlock   (fragment)
//   @group(1) @binding(0..7)  var samp_tex0..7 : texture_2d_array<f32>  (fragment)
//   @group(1) @binding(8..15) var samp_smp0..7 : sampler                (fragment)
// (dynamic-sampler-indexing OFF => 8 SEPARATE scalar texture+sampler bindings,
//  NOT a binding_array; avoids Dawn's gated sized_binding_array feature.)
// Entry points: both stages expose @vertex/@fragment fn main(...).

#pragma once

namespace WGPU
{
inline constexpr char UBER_VERTEX_WGSL[] = R"${delim}(
${vert})${delim}";

inline constexpr char UBER_FRAGMENT_WGSL[] = R"${delim}(
${frag})${delim}";
}  // namespace WGPU
`;
fs.writeFileSync('dolphin-src/Source/Core/VideoBackends/WGPU/WGPUUberShaders.h', hdr);
console.log('wrote WGPUUberShaders.h vert=' + vert.length + ' frag=' + frag.length);
